DROP POLICY IF EXISTS "Authenticated users can upload documents" ON customer_documents;
DROP POLICY IF EXISTS "Users can view their documents" ON customer_documents;
DROP POLICY IF EXISTS "Users can update matched documents" ON customer_documents;
DROP POLICY IF EXISTS "Users can view matching logs for their documents" ON document_matching_logs;

CREATE POLICY "Users can insert documents" ON customer_documents FOR INSERT TO authenticated WITH CHECK (auth.uid() = uploaded_by);
CREATE POLICY "Users can view own documents" ON customer_documents FOR SELECT TO authenticated USING (uploaded_by = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('admin', 'lead_generator')));
CREATE POLICY "Users can update own documents" ON customer_documents FOR UPDATE TO authenticated USING (uploaded_by = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')) WITH CHECK (uploaded_by = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Users can view matching logs" ON document_matching_logs FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM customer_documents WHERE customer_documents.id = document_matching_logs.document_id AND (customer_documents.uploaded_by = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('admin', 'lead_generator')))));
CREATE POLICY "Users can insert matching logs" ON document_matching_logs FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM customer_documents WHERE customer_documents.id = document_id AND customer_documents.uploaded_by = auth.uid()) OR EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));